// <auto-generated />
using ItSys.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ItSys.EntityFramework.Migrations
{
    [DbContext(typeof(ItSysDbContext))]
    partial class ItSysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ItSys.Model.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("Url");

                    b.Property<string>("_url");

                    b.HasKey("Id");

                    b.ToTable("SysUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
